export enum Configuration {
    PORT = 'PORT',
    JWT_SECRET = 'JWT_SECRET',
    GMAIL_ACCOUNT = 'GMAIL_ACCOUNT',
    GMAIL_PASSWORD = 'GMAIL_PASSWORD',
    SERVICE = 'SERVICE',
    //URL FRONTEND SERVICES
    URL_FRONTEND= 'URL_FRONTEND'
}